# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: "root"
        password: ${{secrets.PASSWORD}}
        port: 22
        script: |
          echo cd / && cd home/go/Ai &&
          git clone https://github.com/Zjs-7579/Go_ChatGPT.git &&
          go mod tidy && go build main.go && chmod 777 ./main &&
          setsid ./main


